FROM golang:1.22-alpine AS builder

WORKDIR /build

COPY src/ ./
RUN go mod download
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o nurgle .

FROM scratch

COPY --from=builder /build/nurgle /nurgle

ENTRYPOINT ["/nurgle"]
